"""
AI Tools Integration — Shannon, LuaN1ao, CAI, SmartGuard patterns.
Adapted from web3-ai-tools SKILL.md.
Provides detection patterns for AI-generated code and integration guides.
"""
import logging
import re
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# Patterns that indicate AI-generated code (from SolAgent paper findings)
_AI_CODE_SIGNATURES = [
    # AI code: comprehensive NatSpec but misses edge cases
    r"@notice[^@]*@param[^@]*@return",
    # AI code: defensive redundancy (lots of require statements)
    r"require\([^)]+\);\s*require\([^)]+\);\s*require\([^)]+\);",
    # AI code: modifier + CEI used correctly, but misses cross-function case
    r"nonReentrant\b",
    # AI-generated comments
    r"// AI generated\b",
    r"// Generated by\b",
    r"// Copilot\b",
]

# AI code specific vulnerabilities (things Slither misses)
_AI_MISSED_VULNS = [
    {
        "name": "Cross-function reentrancy via shared state",
        "pattern": "CEI in function A, shared state with function B without nonReentrant",
        "severity": "Critical",
        "detect": "Check: do ALL functions that write to the same state variable have nonReentrant?",
    },
    {
        "name": "Off-by-one at boundaries",
        "pattern": "Tests cover normal range, not boundary+1",
        "severity": "High",
        "detect": "Check: for every `>` comparison, what happens when A == B?",
    },
    {
        "name": "Missing state on error path",
        "pattern": "Happy path updates state, revert path doesn't",
        "severity": "High",
        "detect": "Check: for every early return, which state updates happen in normal path but not here?",
    },
    {
        "name": "Sibling function access control",
        "pattern": "One function has guard, sibling doesn't",
        "severity": "Critical",
        "detect": "Check: do all functions in a 'family' (vote/poke/reset, deposit/withdraw) have the same modifiers?",
    },
    {
        "name": "Constructor role grants missing",
        "pattern": "Role defined but never assigned in constructor",
        "severity": "High",
        "detect": "Check: is every role referenced in onlyRole() actually granted in constructor or initializer?",
    },
]


def detect_ai_generated(code: str) -> Dict:
    """Detect if code appears AI-generated and flag specific weaknesses."""
    signals = []
    for sig in _AI_CODE_SIGNATURES:
        if re.search(sig, code, re.IGNORECASE):
            signals.append(sig)
    
    lines = code.split("\n")
    natsec_count = sum(1 for l in lines if l.strip().startswith(("@notice", "@param", "@return")))
    require_count = sum(1 for l in lines if "require(" in l)
    nonreentrant_count = sum(1 for l in lines if "nonReentrant" in l)
    
    ai_likely = (
        natsec_count > 20 and require_count > 10 and nonreentrant_count > 0
    )
    
    return {
        "ai_likely": ai_likely,
        "signals_found": len(signals),
        "natsec_count": natsec_count,
        "require_count": require_count,
        "nonreentrant_count": nonreentrant_count,
    }


def check_ai_vulnerabilities(code: str) -> List[Dict]:
    """Check for the specific vulnerability classes AI-generated code misses."""
    findings = []
    
    # Get all state variables that two+ functions write
    lines = code.split("\n")
    state_vars = set()
    for line in lines:
        s = line.strip()
        if re.match(r"^\s*(uint|int|bool|address|mapping|bytes)\b", s) and ";" in s:
            var_name = s.split()[1] if len(s.split()) > 1 else ""
            var_name = var_name.split("(")[0].split("[")[0].rstrip(";")
            if var_name:
                state_vars.add(var_name)
    
    # Find functions that write to each state var
    var_writers = {v: [] for v in state_vars}
    for i, line in enumerate(lines):
        for var in state_vars:
            if f"{var} " in line and any(op in line for op in ["=", "+=", "-=", "*="]):
                var_writers[var].append({"line": i + 1, "content": line.strip()})
    
    # Flag vars written by multiple functions without consistent guards
    for var, writers in var_writers.items():
        if len(writers) >= 2:
            writer_lines = [w["line"] for w in writers]
            # Check if all writers have same guard patterns
            guard_counts = {}
            for w in writers:
                line = lines[w["line"] - 1] if w["line"] <= len(lines) else ""
                has_nr = "nonReentrant" in line
                has_only = "only" in line or "onlyRole" in line
                guard_key = f"nr={has_nr},only={has_only}"
                guard_counts[guard_key] = guard_counts.get(guard_key, 0) + 1
            if len(guard_counts) > 1:
                findings.append({
                    "name": f"Inconsistent guards on shared state `{var}`",
                    "severity": "High",
                    "description": f"Variable written by {len(writers)} functions with different guard patterns",
                    "writers": writer_lines,
                })
    
    # Check for roles defined but never granted
    roles_defined = set()
    roles_granted = set()
    for line in lines:
        m = re.search(r"bytes32\s+(\w+_ROLE)\s*=", line)
        if m:
            roles_defined.add(m.group(1))
        if "grantRole(" in line or "_grantRole(" in line or "_setupRole(" in line:
            roles_granted.add(line.strip())
    if roles_defined and len(roles_granted) == 0:
        findings.append({
            "name": f"Roles defined ({len(roles_defined)}) but never granted",
            "severity": "High",
            "description": f"Roles: {', '.join(roles_defined)} — may be permanently locked",
        })
    
    return findings


def format_ai_findings(ai_check: Dict, vulns: List[Dict]) -> str:
    """Format AI tool findings into a readable report."""
    lines = ["### AI Code Analysis"]
    if ai_check.get("ai_likely"):
        lines.append("\n**⚠ Code appears AI-generated** — extra scrutiny recommended:")
        lines.append(f"- NatSpec comments: {ai_check['natsec_count']}")
        lines.append(f"- Require statements: {ai_check['require_count']}")
        lines.append(f"- nonReentrant usages: {ai_check['nonreentrant_count']}")
    
    if vulns:
        lines.append("\n**AI-Specific Vulnerability Classes Detected:**")
        for v in vulns:
            lines.append(f"\n- **[{v['severity']}]** {v['name']}")
            lines.append(f"  {v['description']}")
    
    lines.append("\n**Known AI Code Weaknesses (Slither misses these):**")
    for v in _AI_MISSED_VULNS:
        lines.append(f"- {v['name']} ({v['severity']}): {v['detect']}")
    
    return "\n".join(lines)
