"""
HackerOne-Format Report Generator.
Produces reports compatible with HackerOne's submission format.
"""
import re
import time
from typing import Dict, List, Optional, Tuple

from cvss_scorer import score_report, cvss_explanation


def _extract_findings(report: str) -> List[Dict]:
    findings = []
    lines = report.split("\n")
    current = {}
    for line in lines:
        s = line.strip()
        if s.startswith("- **Name**"):
            if current and current.get("name"):
                findings.append(current)
            current = {"name": s.split(":", 1)[1].strip() if ":" in s else ""}
        elif s.startswith("- **Severity**") and current:
            current["severity"] = s.split(":", 1)[1].strip().rstrip("*") if ":" in s else "Medium"
        elif s.startswith("- **Description**") and current:
            desc = s.split(":", 1)[1].strip() if ":" in s else ""
            current["description"] = desc
        elif s.startswith("- **Exploit**") and current:
            current["exploit"] = s.split(":", 1)[1].strip() if ":" in s else ""
        elif s.startswith("- **Fix**") and current:
            current["fix"] = s.split(":", 1)[1].strip() if ":" in s else ""
        elif s.startswith("- **PoC**") and current:
            current["poc"] = s.split(":", 1)[1].strip() if ":" in s else ""
    if current and current.get("name"):
        findings.append(current)
    return findings


def _extract_rating(report: str) -> str:
    m = re.search(r"### Overall Security Rating:\s*(\S+)", report)
    return m.group(1) if m else "N/A"


def _extract_gas(report: str) -> str:
    m = re.search(r"(### Gas Optimizations.*?)(?=###|$)", report, re.DOTALL)
    return m.group(1).strip() if m else ""


def generate_h1_report(report: str, code: str = "", label: str = "Smart Contract") -> str:
    """Convert an audit report to HackerOne-compatible markdown."""
    findings = _extract_findings(report)
    rating = _extract_rating(report)
    gas = _extract_gas(report)
    cvss = score_report(report)

    lines = [
        f"# Security Audit Report: {label}",
        "",
        f"**Date**: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}",
        f"**Overall Security Rating**: {rating}",
        f"**CVSS 4.0 Max Score**: {cvss['overall_score']}/10 ({cvss['overall_severity']})",
        f"**Total Findings**: {cvss['total_findings']}",
        "",
        "---",
        "",
    ]

    for i, finding in enumerate(cvss["findings"], 1):
        orig = next((f for f in findings if f.get("name") == finding["name"]), {})
        lines.extend([
            f"## Vulnerability #{i}: {finding['name']}",
            "",
            f"**Severity**: {finding['severity']}",
            f"**CVSS 4.0 Score**: {finding['cvss_score']}/10 ({finding['cvss_severity']})",
            f"**CVSS Vector**: `{finding['cvss_vector']}`",
            "",
            f"### Description",
            orig.get("description", "No description provided."),
            "",
        ])
        if orig.get("exploit"):
            lines.extend([
                "### Steps to Reproduce",
                orig["exploit"],
                "",
            ])
        if orig.get("poc"):
            lines.extend([
                "### Proof of Concept",
                f"```solidity",
                orig["poc"],
                f"```",
                "",
            ])
        if orig.get("fix"):
            lines.extend([
                "### Remediation",
                orig["fix"],
                "",
            ])
        lines.append("---")
        lines.append("")

    if gas:
        lines.extend([
            "## Gas Optimizations",
            "",
            gas,
            "",
        ])

    # CVSS appendix
    lines.extend([
        "## CVSS 4.0 Breakdown",
        "",
        cvss_explanation(cvss["overall_score"], cvss["overall_severity"],
                         f"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N"),
        "",
        "---",
        "",
        "*Report generated by Smart Contract Auditor*",
    ])

    return "\n".join(lines)


def generate_h1_short(report: str, label: str = "Smart Contract") -> str:
    """Generate a concise HackerOne report, suitable for copy-paste."""
    findings = _extract_findings(report)
    rating = _extract_rating(report)
    cvss = score_report(report)

    lines = [
        f"## Summary",
        f"- **Asset**: {label}",
        f"- **Severity**: {cvss['overall_severity']} (CVSS 4.0: {cvss['overall_score']}/10)",
        f"- **Rating**: {rating}",
        "",
        f"## Vulnerability Details",
        "",
    ]

    for i, finding in enumerate(cvss["findings"], 1):
        lines.append(f"### {i}. {finding['name']}")
        lines.append(f"**CVSS**: {finding['cvss_score']}/10 | **Severity**: {finding['severity']}")
        lines.append("")

    lines.append("")
    lines.append("## Impact")
    lines.append("As described in each finding above.")
    lines.append("")
    lines.append("## Recommendation")
    lines.append("Apply the fixes described in the full report.")
    lines.append("")

    return "\n".join(lines)
