"""
Platform Report Generator
Generates a report ready for submission per bounty platform.

Supported platforms:
  - Code4rena / Cantina
  - Immunefi
  - Sherlock
  - Hats Finance
  - HackenProof
  - General

Usage:
  py platform_report.py --findings verified_report.md --platform code4rena
  py platform_report.py --findings verified_report.md --platform immunefi --output report.md
"""
import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import List, Optional

# ─── Platform definitions ───

PLATFORMS = {
    "cantina": {
        "name": "Cantina (exact format)",
        "fields": [
            "## Summary",
            "## Finding Description",
            "## Impact Explanation",
            "## Likelihood Explanation",
            "## Proof of Concept",
            "## Recommendation",
        ],
        "note": "Matches Cantina's official format. Submit each finding as a separate Finding.",
    },
    "code4rena": {
        "name": "Code4rena / Cantina",
        "fields": [
            "## Summary",
            "## Vulnerability Details",
            "## Impact",
            "## Proof of Concept",
            "## Tools Used",
            "## Recommended Mitigation",
        ],
        "note": "Use Markdown. Add `### Found by: @username` in the header.",
    },
    "immunefi": {
        "name": "Immunefi",
        "fields": [
            "**Platform:** Immunefi",
            "**Severity:** Critical / High / Medium / Low",
            "**Title:**",
            "**Description:**",
            "**Impact:**",
            "**Proof of Concept:**",
            "**Recommended Fix:**",
            "**References:**",
        ],
        "note": "PDF preferred. Markdown also accepted. Include the full vulnerability title.",
    },
    "sherlock": {
        "name": "Sherlock",
        "fields": [
            "## Summary",
            "## Vulnerability Detail",
            "## Impact",
            "## Code Snippet",
            "## Tool used",
            "## Recommendation",
        ],
        "note": "Use Markdown. One finding per file. Do not include more than one finding in a single report.",
    },
    "hats": {
        "name": "Hats Finance",
        "fields": [
            "**Severity:** Critical / High / Medium / Low",
            "**Title:**",
            "**Contract:**",
            "**Description:**",
            "**Impact:**",
            "**Proof of Concept:**",
            "**Recommended Mitigation Steps:**",
        ],
        "note": "Use Markdown. Include the line number if possible.",
    },
    "hackenproof": {
        "name": "HackenProof (exact format)",
        "fields": [
            "**Category:**",
            "**Severity:**",
            "**1. Title**",
            "**2. Vulnerability details**",
            "**3. Validation steps**",
            "**4. Supporting files / PoC**",
        ],
        "note": "Matches HackenProof's official format. Choose Category from the dropdown. Upload PoC as a zip.",
    },
    "general": {
        "name": "General",
        "fields": [
            "## Title",
            "## Severity",
            "## Description",
            "## Impact",
            "## Proof of Concept",
            "## Recommended Fix",
        ],
        "note": "Generic Markdown format. Suitable for any platform.",
    },
}


@dataclass
class Finding:
    severity: str
    title: str
    file: str
    description: str
    fix: str = ""
    code: str = ""


def parse_verified_report(path: str) -> List[Finding]:
    """Reads verify_findings.py report and extracts findings"""
    if not os.path.exists(path):
        print(f"file not found: {path}")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    findings = []
    # Match: ### [Severity] AgentName -- file.ext  then **Description:** ...
    pattern = r"### \[(Critical|High|Medium|Low|Info)\]\s*(.*?)\s*[—–-]+\s*(.+?)\s*\n+\s*\*\*Description:\*\*\s*(.*?)(?=\n###\s|$)"
    for m in re.finditer(pattern, text, re.DOTALL):
        sev = m.group(1)
        title = m.group(2).strip()
        file = m.group(3).strip().strip("`").strip()
        desc = m.group(4).strip()
        fix = ""
        fm = re.search(r"\*\*Recommended Fix:\*\*\s*(.*)", desc)
        if fm:
            fix = fm.group(1).strip()
        findings.append(Finding(sev, title, file, desc, fix))

    return findings


def generate_platform_report(findings: List[Finding], platform: str) -> str:
    cfg = PLATFORMS.get(platform, PLATFORMS["general"])
    lines = []
    lines.append(f"# Security Audit Report — {cfg['name']}")
    lines.append("")
    lines.append(f"*Generated by Smart Contract Auditor Tool*")
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, f in enumerate(findings, 1):
        lines.append(f"## Finding #{i}: [{f.severity}] {f.title}")
        lines.append("")
        lines.append(f"**File:** `{f.file}`")
        lines.append("")

        if platform in ("code4rena", "cantina"):
            lines.append("## Summary")
            lines.append("A short summary of the issue, keep it brief.")
            lines.append("")
            lines.append(f"{f.description[:200]}")
            lines.append("")
            lines.append("## Finding Description")
            lines.append("A more detailed explanation of the issue.")
            lines.append("")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("## Impact Explanation")
            lines.append("Elaborate on why you've chosen a particular impact assessment.")
            lines.append("")
            lines.append(f"{_impact_desc(f.severity, f.title)}")
            lines.append("")
            lines.append("## Likelihood Explanation")
            lines.append("Explain how likely this is to occur and why.")
            lines.append("")
            lines.append("Medium — requires specific conditions to be exploitable." if f.severity in ("Medium", "Low") else
                         "High — can be triggered with standard user inputs.")
            lines.append("")
            lines.append("## Proof of Concept")
            lines.append("A proof of concept is required for Critical, High and Medium submissions.")
            lines.append("")
            lines.append(f"**File:** `{f.file}`")
            if f.code:
                lines.append("")
                lines.append("```solidity")
                lines.append(f"{f.code}")
                lines.append("```")
            lines.append("")
            lines.append("## Recommendation")
            lines.append("How can the issue be fixed or solved.")
            lines.append("")
            lines.append(f"{f.fix}" if f.fix else "*(add recommended fix here)*")
            lines.append("")

        elif platform == "immunefi":
            lines.append(f"**Platform:** Immunefi")
            lines.append(f"**Severity:** {f.severity}")
            lines.append(f"**Title:** {f.title}")
            lines.append("")
            lines.append("**Description:**")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("**Impact:**")
            lines.append(f"{_impact_desc(f.severity, f.title)}")
            lines.append("")
            if f.fix:
                lines.append("**Recommended Fix:**")
                lines.append(f"{f.fix}")
                lines.append("")
            lines.append("**References:**")
            lines.append("-")

        elif platform == "sherlock":
            lines.append("## Summary")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("## Vulnerability Detail")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("## Impact")
            lines.append(f"{_impact_desc(f.severity, f.title)}")
            lines.append("")
            lines.append("## Code Snippet")
            lines.append(f"`{f.file}`")
            lines.append("")
            lines.append("## Tool used")
            lines.append("Smart Contract Auditor Tool")
            lines.append("")
            if f.fix:
                lines.append("## Recommendation")
                lines.append(f"{f.fix}")
                lines.append("")

        elif platform == "hats":
            lines.append(f"**Severity:** {f.severity}")
            lines.append(f"**Title:** {f.title}")
            lines.append(f"**Contract:** `{f.file}`")
            lines.append("")
            lines.append("**Description:**")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("**Impact:**")
            lines.append(f"{_impact_desc(f.severity, f.title)}")
            lines.append("")
            lines.append("**Proof of Concept:**")
            lines.append("*(add PoC here)*")
            lines.append("")
            if f.fix:
                lines.append("**Recommended Mitigation Steps:**")
                lines.append(f"{f.fix}")
                lines.append("")

        elif platform == "hackenproof":
            cat = _hacken_category(f.title)
            lines.append(f"**Category:** {cat}")
            lines.append("")
            lines.append(f"**Severity:** {f.severity}")
            lines.append("")
            lines.append("---")
            lines.append("")
            lines.append("## 1. Title")
            lines.append(f"{f.title} in `{f.file}`")
            lines.append("")
            lines.append("## 2. Vulnerability details")
            lines.append("What is the vulnerability? In clear steps, how do you reproduce it?")
            lines.append("")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("**Steps to reproduce:**")
            lines.append(f"1. Identify the vulnerable function in `{f.file}`")
            lines.append("2. Trigger the function with a crafted input")
            lines.append("3. Observe the unexpected behavior")
            lines.append("")
            lines.append("## 3. Validation steps")
            lines.append("A clear, logical explanation helps us validate your vulnerability quickly.")
            lines.append("")
            imp = _impact_desc(f.severity, f.title)
            lines.append(f"This is a {cat.lower()} vulnerability in `{f.file}`. The {f.severity.lower()} severity is due to {imp[:100].lower()}")
            lines.append("")
            lines.append("## 4. Supporting files / PoC")
            lines.append("Upload screenshot or other media to support your submission.")
            lines.append("")
            lines.append(f"**Affected file:** `{f.file}`")
            lines.append("")

        else:  # general
            lines.append(f"## Title")
            lines.append(f"{f.title}")
            lines.append("")
            lines.append(f"## Severity")
            lines.append(f"{f.severity}")
            lines.append("")
            lines.append("## Description")
            lines.append(f"{f.description}")
            lines.append("")
            lines.append("## Impact")
            lines.append(f"{_impact_desc(f.severity, f.title)}")
            lines.append("")
            lines.append("## Proof of Concept")
            lines.append(f"`{f.file}`")
            lines.append("")
            if f.fix:
                lines.append("## Recommended Fix")
                lines.append(f"{f.fix}")
                lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(f"*Report prepared for {cfg['name']} by Smart Contract Auditor Tool*")
    return "\n".join(lines)


def validate_markdown(text: str) -> List[str]:
    """Validates the report before saving: checks for common Markdown errors."""
    issues = []
    # Unclosed code blocks
    opens = [i for i, line in enumerate(text.split("\n"), 1) if line.strip().startswith("```")]
    if len(opens) % 2 != 0:
        issues.append(f"⚠️  Unclosed code block (starts at line {opens[-1]})")

    # Broken Markdown links [text](url)
    for m in re.finditer(r'\[([^\]]*)\]\(([^)]*)\)', text):
        url = m.group(2).strip()
        if url and not re.match(r'^https?://', url):
            issues.append(f"⚠️  Invalid link: '{m.group(0)}'")

    # Incomplete tables (column count mismatch)
    table_starts = [i for i, line in enumerate(text.split("\n")) if "|" in line and "---" in line]
    for ts in table_starts:
        lines = text.split("\n")
        before = lines[ts - 1].count("|") if ts > 0 else 0
        sep_count = lines[ts].count("|")
        after = lines[ts + 1].count("|") if ts + 1 < len(lines) else 0
        if before != sep_count or after != sep_count:
            issues.append(f"⚠️  Table column mismatch near line {ts + 1}")

    return issues


def _hacken_category(title: str) -> str:
    """Maps agent/title to HackenProof category"""
    t = title.lower()
    if "reentrancy" in t or "call.value" in t or "low-level" in t or "call" in t:
        return "Reentrancy"
    if "overflow" in t or "underflow" in t or "integer" in t:
        return "Integer Underflow"
    if "timestamp" in t or "time" in t:
        return "Timestamp Dependence"
    if "access" in t or "owner" in t or "onlyowner" in t or "centraliz" in t:
        return "Broken Access Control (BAC)"
    if "dos" in t or "loop" in t or "gas" in t or "unbounded" in t:
        return "DoS with Block Gas Limit"
    if "selfdestruct" in t or "destroy" in t:
        return "Forcibly Sending Ether to a Contract"
    if "front" in t or "tod" in t or "race" in t:
        return "Transaction-Ordering Dependence (TOD) / Front Running"
    if "flash" in t or "loan" in t:
        return "Business Logic Errors"
    if "delegatecall" in t:
        return "Improper Access Control"
    if "proxy" in t or "uninitialized" in t:
        return "Authentication Bypass"
    if "tx.origin" in t:
        return "Insecure Authorization"
    if "assembly" in t or "inline" in t:
        return "Code Injection"
    if "unchecked" in t or "return" in t:
        return "Best Practices Not Enforced"
    if "mint" in t or "burn" in t or "public" in t:
        return "Broken Access Control (BAC)"
    if "hash" in t or "size" in t or "validation" in t:
        return "Insufficient Cryptography"
    if "coin" in t or "amount" in t or "negative" in t:
        return "Business Logic Errors"
    if "type" in t or "confusion" in t or "bypass" in t:
        return "Type Confusion"
    if "collateral" in t or "ratio" in t or "economic" in t:
        return "Business Logic Errors"
    if "payout" in t or "hijack" in t:
        return "Privilege Escalation"
    if "vault" in t or "launch" in t or "state" in t:
        return "Business Logic Errors"
    if "message" in t or "mode" in t:
        return "Improper Authentication"
    if "oracle" in t or "price" in t:
        return "Business Logic Errors"
    if "address" in t or "unvalidated" in t or "validation" in t:
        return "Improper Input Validation"
    if "safe" in t or "transfer" in t:
        return "Best Practices Not Enforced"
    if "event" in t or "pragma" in t:
        return "Best Practices Not Enforced"
    if "magic" in t or "naming" in t:
        return "Code Tampering"
    return "Other"


def _impact_desc(severity: str, title: str) -> str:
    impacts = {
        "Critical": "Complete loss of funds or contract destruction.",
        "High": "Partial loss of funds or breakage of a core function.",
        "Medium": "Unexpected behavior or limited privilege bypass.",
        "Low": "Violation of best practices or readability issue.",
        "Info": "Additional information with no direct security impact.",
    }
    return impacts.get(severity, "Security impact requiring assessment.")


def prompt_platform():
    print()
    print("Choose a bounty platform:")
    print()
    keys = list(PLATFORMS.keys())
    for i, k in enumerate(keys, 1):
        print(f"  {i}. {PLATFORMS[k]['name']}")
    print()
    try:
        choice = int(input("Platform number: ").strip())
        if 1 <= choice <= len(keys):
            return keys[choice - 1]
    except ValueError:
        pass
    print("⚠️  Invalid choice. Using the general format.")
    return "general"


def main():
    parser = argparse.ArgumentParser(description="Generate platform-specific audit report")
    parser.add_argument("--findings", help="Verified findings file from verify_findings.py")
    parser.add_argument("--platform", choices=list(PLATFORMS.keys()) + ["ask"],
                        default="ask", help="Target platform")
    parser.add_argument("--output", default="", help="Output file")
    args = parser.parse_args()

    # If findings not specified, ask
    findings_path = args.findings
    if not findings_path:
        findings_path = input("Path to findings file (from verify_findings.py): ").strip()
        if not findings_path:
            findings_path = "verified_report.md"

    findings = parse_verified_report(findings_path)
    if not findings:
        print("⚠️  No findings found in the file. Make sure the file contains findings in the format:")
        print('  ### [Critical] Title — `file.sol`')
        print('  **Description:** ...')
        return

    print(f"✓ Found {len(findings)} findings in the file")

    # Platform selection
    platform = args.platform
    if platform == "ask":
        platform = prompt_platform()

    cfg = PLATFORMS.get(platform, PLATFORMS["general"])
    print(f"✓ Platform: {cfg['name']}")

    report = generate_platform_report(findings, platform)

    # Save or print
    output = args.output
    if not output:
        default_name = f"report_{platform}.md"
        output = input(f"Report file name [{default_name}]: ").strip() or default_name

    with open(output, "w", encoding="utf-8") as f:
        f.write(report)

    issues = validate_markdown(report)
    if issues:
        print("⚠️  Validation warnings:")
        for iss in issues:
            print(f"  {iss}")
        print()

    print(f"✓ Report saved: {output}")
    print()
    print(f"Note: {cfg['note']}")
    print()


if __name__ == "__main__":
    main()
